clusterName: fake-cluster
splunkObservability:
  realm: fake-realm
  accessToken: fake-token

  tracesEnabled: false
  metricsEnabled: false

splunkPlatform:
  endpoint: "fake-endpoint"
  # Required for Splunk Enterprise/Cloud (if `endpoint` is specified). Splunk
  # HTTP Event Collector token.
  token: "fake-token"

  index: "main"

  logsEnabled: true
  metricsEnabled: false

logsEngine: otel
